<?php
set_time_limit(0);
require('conexionmysqli.inc');

$sql = "update salida_detalle_almacenes set costo_almacen=17.346 where cod_material=1;
update salida_detalle_almacenes set costo_almacen=17.346 where cod_material=2;
update salida_detalle_almacenes set costo_almacen=19.12 where cod_material=4;
update salida_detalle_almacenes set costo_almacen=19.12 where cod_material=5;
update salida_detalle_almacenes set costo_almacen=19.12 where cod_material=6;
update salida_detalle_almacenes set costo_almacen=21.087 where cod_material=7;
update salida_detalle_almacenes set costo_almacen=21.087 where cod_material=8;
update salida_detalle_almacenes set costo_almacen=23.249 where cod_material=10;
update salida_detalle_almacenes set costo_almacen=23.249 where cod_material=12;
update salida_detalle_almacenes set costo_almacen=18.864 where cod_material=13;
update salida_detalle_almacenes set costo_almacen=18.864 where cod_material=14;
update salida_detalle_almacenes set costo_almacen=18.864 where cod_material=15;
update salida_detalle_almacenes set costo_almacen=60.757 where cod_material=16;
update salida_detalle_almacenes set costo_almacen=60.757 where cod_material=17;
update salida_detalle_almacenes set costo_almacen=22.561 where cod_material=18;
update salida_detalle_almacenes set costo_almacen=22.561 where cod_material=19;
update salida_detalle_almacenes set costo_almacen=17.823 where cod_material=20;
update salida_detalle_almacenes set costo_almacen=28.305 where cod_material=24;
update salida_detalle_almacenes set costo_almacen=28.305 where cod_material=25;
update salida_detalle_almacenes set costo_almacen=38.628 where cod_material=27;
update salida_detalle_almacenes set costo_almacen=45.536 where cod_material=28;
update salida_detalle_almacenes set costo_almacen=45.536 where cod_material=29;
update salida_detalle_almacenes set costo_almacen=51.774 where cod_material=31;
update salida_detalle_almacenes set costo_almacen=55.639 where cod_material=32;
update salida_detalle_almacenes set costo_almacen=55.639 where cod_material=33;
update salida_detalle_almacenes set costo_almacen=36.034 where cod_material=34;
update salida_detalle_almacenes set costo_almacen=36.034 where cod_material=35;
update salida_detalle_almacenes set costo_almacen=48.986 where cod_material=37;
update salida_detalle_almacenes set costo_almacen=225.397 where cod_material=38;
update salida_detalle_almacenes set costo_almacen=225.397 where cod_material=39;
update salida_detalle_almacenes set costo_almacen=329.882 where cod_material=40;
update salida_detalle_almacenes set costo_almacen=329.882 where cod_material=41;
update salida_detalle_almacenes set costo_almacen=53.61 where cod_material=42;
update salida_detalle_almacenes set costo_almacen=59.671 where cod_material=43;
update salida_detalle_almacenes set costo_almacen=73.232 where cod_material=44;
update salida_detalle_almacenes set costo_almacen=49.736 where cod_material=45;
update salida_detalle_almacenes set costo_almacen=55.436 where cod_material=46;
update salida_detalle_almacenes set costo_almacen=53.054 where cod_material=47;
update salida_detalle_almacenes set costo_almacen=61.251 where cod_material=48;
update salida_detalle_almacenes set costo_almacen=37.402 where cod_material=49;
update salida_detalle_almacenes set costo_almacen=37.402 where cod_material=50;
update salida_detalle_almacenes set costo_almacen=37.402 where cod_material=51;
update salida_detalle_almacenes set costo_almacen=42.166 where cod_material=52;
update salida_detalle_almacenes set costo_almacen=42.166 where cod_material=53;
update salida_detalle_almacenes set costo_almacen=42.166 where cod_material=54;
update salida_detalle_almacenes set costo_almacen=77.794 where cod_material=55;
update salida_detalle_almacenes set costo_almacen=77.794 where cod_material=56;
update salida_detalle_almacenes set costo_almacen=77.794 where cod_material=57;
update salida_detalle_almacenes set costo_almacen=46.869 where cod_material=58;
update salida_detalle_almacenes set costo_almacen=52.807 where cod_material=59;
update salida_detalle_almacenes set costo_almacen=64.436 where cod_material=60;
update salida_detalle_almacenes set costo_almacen=95.714 where cod_material=61;
update salida_detalle_almacenes set costo_almacen=95.714 where cod_material=62;
update salida_detalle_almacenes set costo_almacen=55.436 where cod_material=63;
update salida_detalle_almacenes set costo_almacen=41.01 where cod_material=64;
update salida_detalle_almacenes set costo_almacen=71.238 where cod_material=65;
update salida_detalle_almacenes set costo_almacen=50.019 where cod_material=66;
update salida_detalle_almacenes set costo_almacen=50.566 where cod_material=67;
update salida_detalle_almacenes set costo_almacen=24.308 where cod_material=68;
update salida_detalle_almacenes set costo_almacen=24.308 where cod_material=69;
update salida_detalle_almacenes set costo_almacen=14.232 where cod_material=70;
update salida_detalle_almacenes set costo_almacen=10.65 where cod_material=71;
update salida_detalle_almacenes set costo_almacen=18.176 where cod_material=72;
update salida_detalle_almacenes set costo_almacen=12.979 where cod_material=73;
update salida_detalle_almacenes set costo_almacen=12.829 where cod_material=74;
update salida_detalle_almacenes set costo_almacen=4.526 where cod_material=75;
update salida_detalle_almacenes set costo_almacen=3.688 where cod_material=76;
update salida_detalle_almacenes set costo_almacen=3.785 where cod_material=77;
update salida_detalle_almacenes set costo_almacen=3.776 where cod_material=78;
update salida_detalle_almacenes set costo_almacen=3.653 where cod_material=79;
update salida_detalle_almacenes set costo_almacen=3.044 where cod_material=80;
update salida_detalle_almacenes set costo_almacen=3.194 where cod_material=81;
update salida_detalle_almacenes set costo_almacen=2.753 where cod_material=82;
update salida_detalle_almacenes set costo_almacen=14.179 where cod_material=83;
update salida_detalle_almacenes set costo_almacen=11.7 where cod_material=84;
update salida_detalle_almacenes set costo_almacen=11.602 where cod_material=85;
update salida_detalle_almacenes set costo_almacen=10.261 where cod_material=86;
update salida_detalle_almacenes set costo_almacen=8.92 where cod_material=87;
update salida_detalle_almacenes set costo_almacen=6.256 where cod_material=88;
update salida_detalle_almacenes set costo_almacen=12.811 where cod_material=89;
update salida_detalle_almacenes set costo_almacen=54.651 where cod_material=90;
update salida_detalle_almacenes set costo_almacen=44.672 where cod_material=91;
update salida_detalle_almacenes set costo_almacen=45.845 where cod_material=92;
update salida_detalle_almacenes set costo_almacen=45.898 where cod_material=93;
update salida_detalle_almacenes set costo_almacen=44.469 where cod_material=94;
update salida_detalle_almacenes set costo_almacen=36.952 where cod_material=95;
update salida_detalle_almacenes set costo_almacen=38.831 where cod_material=96;
update salida_detalle_almacenes set costo_almacen=33.581 where cod_material=97;
update salida_detalle_almacenes set costo_almacen=12.997 where cod_material=98;
update salida_detalle_almacenes set costo_almacen=11.1 where cod_material=99;
update salida_detalle_almacenes set costo_almacen=95.211 where cod_material=100;
update salida_detalle_almacenes set costo_almacen=27.722 where cod_material=101;
update salida_detalle_almacenes set costo_almacen=33.51 where cod_material=102;
update salida_detalle_almacenes set costo_almacen=39.687 where cod_material=103;
update salida_detalle_almacenes set costo_almacen=58.277 where cod_material=104;
update salida_detalle_almacenes set costo_almacen=77.926 where cod_material=105;
update salida_detalle_almacenes set costo_almacen=19.702 where cod_material=106;
update salida_detalle_almacenes set costo_almacen=24.087 where cod_material=107;
update salida_detalle_almacenes set costo_almacen=32.258 where cod_material=108;
update salida_detalle_almacenes set costo_almacen=9.988 where cod_material=109;
update salida_detalle_almacenes set costo_almacen=10.914 where cod_material=110;
update salida_detalle_almacenes set costo_almacen=12.926 where cod_material=111;
update salida_detalle_almacenes set costo_almacen=52.401 where cod_material=112;
update salida_detalle_almacenes set costo_almacen=46.189 where cod_material=113;
update salida_detalle_almacenes set costo_almacen=28.728 where cod_material=117;
update salida_detalle_almacenes set costo_almacen=18.643 where cod_material=118;
update salida_detalle_almacenes set costo_almacen=35.778 where cod_material=119;
update salida_detalle_almacenes set costo_almacen=1.632 where cod_material=120;
update salida_detalle_almacenes set costo_almacen=1.632 where cod_material=121;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=122;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=123;
update salida_detalle_almacenes set costo_almacen=1.473 where cod_material=124;
update salida_detalle_almacenes set costo_almacen=1.473 where cod_material=125;
update salida_detalle_almacenes set costo_almacen=1.129 where cod_material=126;
update salida_detalle_almacenes set costo_almacen=1.129 where cod_material=127;
update salida_detalle_almacenes set costo_almacen=5.241 where cod_material=128;
update salida_detalle_almacenes set costo_almacen=4.579 where cod_material=129;
update salida_detalle_almacenes set costo_almacen=4.791 where cod_material=130;
update salida_detalle_almacenes set costo_almacen=36.96 where cod_material=131;
update salida_detalle_almacenes set costo_almacen=36.96 where cod_material=132;
update salida_detalle_almacenes set costo_almacen=38.654 where cod_material=133;
update salida_detalle_almacenes set costo_almacen=1.526 where cod_material=134;
update salida_detalle_almacenes set costo_almacen=1.526 where cod_material=135;
update salida_detalle_almacenes set costo_almacen=1.526 where cod_material=136;
update salida_detalle_almacenes set costo_almacen=1.526 where cod_material=137;
update salida_detalle_almacenes set costo_almacen=1.306 where cod_material=138;
update salida_detalle_almacenes set costo_almacen=1.306 where cod_material=139;
update salida_detalle_almacenes set costo_almacen=1.306 where cod_material=140;
update salida_detalle_almacenes set costo_almacen=1.306 where cod_material=141;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=142;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=143;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=144;
update salida_detalle_almacenes set costo_almacen=1.421 where cod_material=145;
update salida_detalle_almacenes set costo_almacen=1.076 where cod_material=146;
update salida_detalle_almacenes set costo_almacen=1.076 where cod_material=147;
update salida_detalle_almacenes set costo_almacen=1.076 where cod_material=148;
update salida_detalle_almacenes set costo_almacen=1.076 where cod_material=149;
update salida_detalle_almacenes set costo_almacen=4.906 where cod_material=150;
update salida_detalle_almacenes set costo_almacen=4.244 where cod_material=152;
update salida_detalle_almacenes set costo_almacen=4.456 where cod_material=154;
update salida_detalle_almacenes set costo_almacen=34.499 where cod_material=156;
update salida_detalle_almacenes set costo_almacen=36.175 where cod_material=157;
update salida_detalle_almacenes set costo_almacen=1.332 where cod_material=158;
update salida_detalle_almacenes set costo_almacen=1.332 where cod_material=159;
update salida_detalle_almacenes set costo_almacen=1.112 where cod_material=160;
update salida_detalle_almacenes set costo_almacen=1.112 where cod_material=161;
update salida_detalle_almacenes set costo_almacen=1.173 where cod_material=162;
update salida_detalle_almacenes set costo_almacen=1.173 where cod_material=163;
update salida_detalle_almacenes set costo_almacen=0.979 where cod_material=164;
update salida_detalle_almacenes set costo_almacen=0.979 where cod_material=165;
update salida_detalle_almacenes set costo_almacen=4.341 where cod_material=166;
update salida_detalle_almacenes set costo_almacen=3.679 where cod_material=167;
update salida_detalle_almacenes set costo_almacen=3.891 where cod_material=168;
update salida_detalle_almacenes set costo_almacen=30.502 where cod_material=169;
update salida_detalle_almacenes set costo_almacen=31.658 where cod_material=170;
update salida_detalle_almacenes set costo_almacen=5.029 where cod_material=171;
update salida_detalle_almacenes set costo_almacen=5.029 where cod_material=172;
update salida_detalle_almacenes set costo_almacen=5.029 where cod_material=173;
update salida_detalle_almacenes set costo_almacen=19.799 where cod_material=174;
update salida_detalle_almacenes set costo_almacen=19.799 where cod_material=175;
update salida_detalle_almacenes set costo_almacen=19.799 where cod_material=176;
update salida_detalle_almacenes set costo_almacen=15.785 where cod_material=177;
update salida_detalle_almacenes set costo_almacen=15.785 where cod_material=178;
update salida_detalle_almacenes set costo_almacen=15.785 where cod_material=179;
update salida_detalle_almacenes set costo_almacen=17.602 where cod_material=180;
update salida_detalle_almacenes set costo_almacen=17.602 where cod_material=181;
update salida_detalle_almacenes set costo_almacen=17.602 where cod_material=182;
update salida_detalle_almacenes set costo_almacen=11.311 where cod_material=183;
update salida_detalle_almacenes set costo_almacen=11.311 where cod_material=184;
update salida_detalle_almacenes set costo_almacen=35.099 where cod_material=186;
update salida_detalle_almacenes set costo_almacen=35.099 where cod_material=187;
update salida_detalle_almacenes set costo_almacen=36.06 where cod_material=188;
update salida_detalle_almacenes set costo_almacen=36.06 where cod_material=189;
update salida_detalle_almacenes set costo_almacen=6.503 where cod_material=190;
update salida_detalle_almacenes set costo_almacen=6.503 where cod_material=191;
update salida_detalle_almacenes set costo_almacen=8.153 where cod_material=192;
update salida_detalle_almacenes set costo_almacen=8.153 where cod_material=193;
update salida_detalle_almacenes set costo_almacen=5.179 where cod_material=194;
update salida_detalle_almacenes set costo_almacen=5.179 where cod_material=195;
update salida_detalle_almacenes set costo_almacen=16.852 where cod_material=197;
update salida_detalle_almacenes set costo_almacen=16.852 where cod_material=198;
update salida_detalle_almacenes set costo_almacen=16.852 where cod_material=199;
update salida_detalle_almacenes set costo_almacen=13.791 where cod_material=201;
update salida_detalle_almacenes set costo_almacen=13.791 where cod_material=202;
update salida_detalle_almacenes set costo_almacen=13.791 where cod_material=203;
update salida_detalle_almacenes set costo_almacen=15.335 where cod_material=205;
update salida_detalle_almacenes set costo_almacen=15.335 where cod_material=206;
update salida_detalle_almacenes set costo_almacen=15.335 where cod_material=207;
update salida_detalle_almacenes set costo_almacen=4.412 where cod_material=208;
update salida_detalle_almacenes set costo_almacen=4.412 where cod_material=209;
update salida_detalle_almacenes set costo_almacen=4.412 where cod_material=210;
update salida_detalle_almacenes set costo_almacen=4.412 where cod_material=211;
update salida_detalle_almacenes set costo_almacen=27.167 where cod_material=212;
update salida_detalle_almacenes set costo_almacen=27.167 where cod_material=213;
update salida_detalle_almacenes set costo_almacen=27.167 where cod_material=214;
update salida_detalle_almacenes set costo_almacen=27.167 where cod_material=215;
update salida_detalle_almacenes set costo_almacen=31.79 where cod_material=217;
update salida_detalle_almacenes set costo_almacen=31.79 where cod_material=218;
update salida_detalle_almacenes set costo_almacen=31.79 where cod_material=219;
update salida_detalle_almacenes set costo_almacen=31.155 where cod_material=220;
update salida_detalle_almacenes set costo_almacen=31.155 where cod_material=221;
update salida_detalle_almacenes set costo_almacen=31.155 where cod_material=222;
update salida_detalle_almacenes set costo_almacen=31.155 where cod_material=223;
update salida_detalle_almacenes set costo_almacen=10.235 where cod_material=224;
update salida_detalle_almacenes set costo_almacen=6.441 where cod_material=225;
update salida_detalle_almacenes set costo_almacen=6.441 where cod_material=226;
update salida_detalle_almacenes set costo_almacen=6.441 where cod_material=227;
update salida_detalle_almacenes set costo_almacen=6.441 where cod_material=228;
update salida_detalle_almacenes set costo_almacen=8.091 where cod_material=229;
update salida_detalle_almacenes set costo_almacen=8.091 where cod_material=230;
update salida_detalle_almacenes set costo_almacen=8.091 where cod_material=231;
update salida_detalle_almacenes set costo_almacen=8.091 where cod_material=232;
update salida_detalle_almacenes set costo_almacen=5.117 where cod_material=233;
update salida_detalle_almacenes set costo_almacen=5.117 where cod_material=234;
update salida_detalle_almacenes set costo_almacen=5.117 where cod_material=235;
update salida_detalle_almacenes set costo_almacen=5.117 where cod_material=236;
update salida_detalle_almacenes set costo_almacen=20.735 where cod_material=237;
update salida_detalle_almacenes set costo_almacen=22.879 where cod_material=238;
update salida_detalle_almacenes set costo_almacen=25.737 where cod_material=239;
update salida_detalle_almacenes set costo_almacen=27.846 where cod_material=240;
update salida_detalle_almacenes set costo_almacen=20.47 where cod_material=242;
update salida_detalle_almacenes set costo_almacen=15.661 where cod_material=244;
update salida_detalle_almacenes set costo_almacen=50.16 where cod_material=245;
update salida_detalle_almacenes set costo_almacen=15.22 where cod_material=246;
update salida_detalle_almacenes set costo_almacen=14.461 where cod_material=247;
update salida_detalle_almacenes set costo_almacen=14.938 where cod_material=248;
update salida_detalle_almacenes set costo_almacen=2.982 where cod_material=249;
update salida_detalle_almacenes set costo_almacen=2.832 where cod_material=250;
update salida_detalle_almacenes set costo_almacen=2.841 where cod_material=253;
update salida_detalle_almacenes set costo_almacen=3.847 where cod_material=261;
update salida_detalle_almacenes set costo_almacen=4.041 where cod_material=262;
update salida_detalle_almacenes set costo_almacen=3.653 where cod_material=263;
update salida_detalle_almacenes set costo_almacen=3.609 where cod_material=264;
update salida_detalle_almacenes set costo_almacen=3.529 where cod_material=265;
update salida_detalle_almacenes set costo_almacen=3.768 where cod_material=266;
update salida_detalle_almacenes set costo_almacen=8.814 where cod_material=267;
update salida_detalle_almacenes set costo_almacen=8.082 where cod_material=268;
update salida_detalle_almacenes set costo_almacen=6.326 where cod_material=269;
update salida_detalle_almacenes set costo_almacen=7.694 where cod_material=270;
update salida_detalle_almacenes set costo_almacen=5.567 where cod_material=273;
update salida_detalle_almacenes set costo_almacen=5.726 where cod_material=274;
update salida_detalle_almacenes set costo_almacen=2.832 where cod_material=276;
update salida_detalle_almacenes set costo_almacen=2.832 where cod_material=277;
update salida_detalle_almacenes set costo_almacen=2.832 where cod_material=278;
update salida_detalle_almacenes set costo_almacen=6.829 where cod_material=279;
update salida_detalle_almacenes set costo_almacen=13.482 where cod_material=280;
update salida_detalle_almacenes set costo_almacen=13.482 where cod_material=281;
update salida_detalle_almacenes set costo_almacen=13.482 where cod_material=282;
update salida_detalle_almacenes set costo_almacen=21.855 where cod_material=283;
update salida_detalle_almacenes set costo_almacen=21.855 where cod_material=284;
update salida_detalle_almacenes set costo_almacen=21.855 where cod_material=285;
update salida_detalle_almacenes set costo_almacen=21.564 where cod_material=286;
update salida_detalle_almacenes set costo_almacen=21.564 where cod_material=287;
update salida_detalle_almacenes set costo_almacen=21.564 where cod_material=288;
update salida_detalle_almacenes set costo_almacen=21.564 where cod_material=289;
update salida_detalle_almacenes set costo_almacen=21.758 where cod_material=290;
update salida_detalle_almacenes set costo_almacen=21.758 where cod_material=291;
update salida_detalle_almacenes set costo_almacen=21.758 where cod_material=293;
update salida_detalle_almacenes set costo_almacen=6.238 where cod_material=294;
update salida_detalle_almacenes set costo_almacen=6.238 where cod_material=295;
update salida_detalle_almacenes set costo_almacen=7.367 where cod_material=296;
update salida_detalle_almacenes set costo_almacen=7.367 where cod_material=297;
update salida_detalle_almacenes set costo_almacen=8.867 where cod_material=298;
update salida_detalle_almacenes set costo_almacen=8.867 where cod_material=299;
update salida_detalle_almacenes set costo_almacen=6.07 where cod_material=300;
update salida_detalle_almacenes set costo_almacen=6.07 where cod_material=301;
update salida_detalle_almacenes set costo_almacen=7.411 where cod_material=302;
update salida_detalle_almacenes set costo_almacen=7.411 where cod_material=303;
update salida_detalle_almacenes set costo_almacen=33.405 where cod_material=304;
update salida_detalle_almacenes set costo_almacen=33.405 where cod_material=305;
update salida_detalle_almacenes set costo_almacen=30.996 where cod_material=307;
update salida_detalle_almacenes set costo_almacen=30.996 where cod_material=308;
update salida_detalle_almacenes set costo_almacen=30.996 where cod_material=309;
update salida_detalle_almacenes set costo_almacen=36.766 where cod_material=310;
update salida_detalle_almacenes set costo_almacen=33.89 where cod_material=311;
update salida_detalle_almacenes set costo_almacen=80.6 where cod_material=312;
update salida_detalle_almacenes set costo_almacen=33.96 where cod_material=313;
update salida_detalle_almacenes set costo_almacen=25.102 where cod_material=314;
update salida_detalle_almacenes set costo_almacen=25.12 where cod_material=315;
update salida_detalle_almacenes set costo_almacen=28.622 where cod_material=316;
update salida_detalle_almacenes set costo_almacen=28.393 where cod_material=317;
update salida_detalle_almacenes set costo_almacen=47.239 where cod_material=318;
update salida_detalle_almacenes set costo_almacen=7.756 where cod_material=322;
update salida_detalle_almacenes set costo_almacen=6.362 where cod_material=323;
update salida_detalle_almacenes set costo_almacen=2.832 where cod_material=324;
update salida_detalle_almacenes set costo_almacen=5.656 where cod_material=325;
update salida_detalle_almacenes set costo_almacen=6.794 where cod_material=326;
update salida_detalle_almacenes set costo_almacen=5.726 where cod_material=327;
update salida_detalle_almacenes set costo_almacen=19.949 where cod_material=328;
update salida_detalle_almacenes set costo_almacen=14.099 where cod_material=329;
update salida_detalle_almacenes set costo_almacen=142.699 where cod_material=332;
update salida_detalle_almacenes set costo_almacen=63.135 where cod_material=333;
update salida_detalle_almacenes set costo_almacen=85.747 where cod_material=334;
update salida_detalle_almacenes set costo_almacen=89.007 where cod_material=335;
update salida_detalle_almacenes set costo_almacen=140.328 where cod_material=336;
update salida_detalle_almacenes set costo_almacen=153.497 where cod_material=337;
update salida_detalle_almacenes set costo_almacen=153.625 where cod_material=338;
update salida_detalle_almacenes set costo_almacen=167.598 where cod_material=339;
update salida_detalle_almacenes set costo_almacen=91.929 where cod_material=340;
update salida_detalle_almacenes set costo_almacen=90.617 where cod_material=341;
update salida_detalle_almacenes set costo_almacen=39.38 where cod_material=342;
update salida_detalle_almacenes set costo_almacen=40.312 where cod_material=343;
update salida_detalle_almacenes set costo_almacen=39.38 where cod_material=344;
update salida_detalle_almacenes set costo_almacen=25.026 where cod_material=345;
update salida_detalle_almacenes set costo_almacen=29.683 where cod_material=347;
update salida_detalle_almacenes set costo_almacen=27.778 where cod_material=350;
update salida_detalle_almacenes set costo_almacen=30.446 where cod_material=351;
update salida_detalle_almacenes set costo_almacen=25.534 where cod_material=353;
update salida_detalle_almacenes set costo_almacen=27.736 where cod_material=354;
update salida_detalle_almacenes set costo_almacen=55.387 where cod_material=356;
update salida_detalle_almacenes set costo_almacen=25.576 where cod_material=357;
update salida_detalle_almacenes set costo_almacen=30.488 where cod_material=359;
update salida_detalle_almacenes set costo_almacen=25.491 where cod_material=361;
update salida_detalle_almacenes set costo_almacen=55.217 where cod_material=364;
update salida_detalle_almacenes set costo_almacen=78.432 where cod_material=365;
update salida_detalle_almacenes set costo_almacen=25.516 where cod_material=366;
update salida_detalle_almacenes set costo_almacen=27.686 where cod_material=367;
update salida_detalle_almacenes set costo_almacen=30.438 where cod_material=368;
update salida_detalle_almacenes set costo_almacen=55.005 where cod_material=369;
update salida_detalle_almacenes set costo_almacen=14.228 where cod_material=370;
update salida_detalle_almacenes set costo_almacen=112.593 where cod_material=371;
update salida_detalle_almacenes set costo_almacen=17.065 where cod_material=373;
update salida_detalle_almacenes set costo_almacen=19.182 where cod_material=374;
update salida_detalle_almacenes set costo_almacen=21.427 where cod_material=375;
update salida_detalle_almacenes set costo_almacen=33.664 where cod_material=377;
update salida_detalle_almacenes set costo_almacen=32.944 where cod_material=378;
update salida_detalle_almacenes set costo_almacen=38.745 where cod_material=379;
update salida_detalle_almacenes set costo_almacen=46.537 where cod_material=380;
update salida_detalle_almacenes set costo_almacen=51.491 where cod_material=381;
update salida_detalle_almacenes set costo_almacen=57.335 where cod_material=382;
update salida_detalle_almacenes set costo_almacen=33.071 where cod_material=383;
update salida_detalle_almacenes set costo_almacen=38.576 where cod_material=384;
update salida_detalle_almacenes set costo_almacen=46.367 where cod_material=385;
update salida_detalle_almacenes set costo_almacen=51.279 where cod_material=386;
update salida_detalle_almacenes set costo_almacen=57.08 where cod_material=387;
update salida_detalle_almacenes set costo_almacen=26.423 where cod_material=388;
update salida_detalle_almacenes set costo_almacen=33.283 where cod_material=389;
update salida_detalle_almacenes set costo_almacen=14.524 where cod_material=390;
update salida_detalle_almacenes set costo_almacen=17.107 where cod_material=391;
update salida_detalle_almacenes set costo_almacen=19.182 where cod_material=392;
update salida_detalle_almacenes set costo_almacen=21.257 where cod_material=393;
update salida_detalle_almacenes set costo_almacen=24.814 where cod_material=394;
update salida_detalle_almacenes set costo_almacen=26.719 where cod_material=395;
update salida_detalle_almacenes set costo_almacen=368.394 where cod_material=396;
update salida_detalle_almacenes set costo_almacen=38.364 where cod_material=397;
update salida_detalle_almacenes set costo_almacen=44.716 where cod_material=398;
update salida_detalle_almacenes set costo_almacen=50.644 where cod_material=399;
update salida_detalle_almacenes set costo_almacen=39.677 where cod_material=400;
update salida_detalle_almacenes set costo_almacen=47.002 where cod_material=401;
update salida_detalle_almacenes set costo_almacen=20.41 where cod_material=402;
update salida_detalle_almacenes set costo_almacen=25.322 where cod_material=403;
update salida_detalle_almacenes set costo_almacen=35.739 where cod_material=405;
update salida_detalle_almacenes set costo_almacen=23.078 where cod_material=406;
update salida_detalle_almacenes set costo_almacen=42.006 where cod_material=409;
update salida_detalle_almacenes set costo_almacen=54.497 where cod_material=410;
update salida_detalle_almacenes set costo_almacen=42.895 where cod_material=411;
update salida_detalle_almacenes set costo_almacen=42.895 where cod_material=412;
update salida_detalle_almacenes set costo_almacen=28.244 where cod_material=413;
update salida_detalle_almacenes set costo_almacen=38.407 where cod_material=414;
update salida_detalle_almacenes set costo_almacen=54.116 where cod_material=416;
update salida_detalle_almacenes set costo_almacen=15.286 where cod_material=417;
update salida_detalle_almacenes set costo_almacen=19.902 where cod_material=418;
update salida_detalle_almacenes set costo_almacen=34.807 where cod_material=419;
update salida_detalle_almacenes set costo_almacen=35.061 where cod_material=421;
update salida_detalle_almacenes set costo_almacen=34.807 where cod_material=422;
update salida_detalle_almacenes set costo_almacen=40.693 where cod_material=425;
update salida_detalle_almacenes set costo_almacen=41.243 where cod_material=428;
update salida_detalle_almacenes set costo_almacen=49.331 where cod_material=429;
update salida_detalle_almacenes set costo_almacen=217.903 where cod_material=430;
update salida_detalle_almacenes set costo_almacen=38.237 where cod_material=431;
update salida_detalle_almacenes set costo_almacen=44.504 where cod_material=432;
update salida_detalle_almacenes set costo_almacen=53.862 where cod_material=433;
update salida_detalle_almacenes set costo_almacen=61.992 where cod_material=434;
update salida_detalle_almacenes set costo_almacen=63.474 where cod_material=435;
update salida_detalle_almacenes set costo_almacen=237.042 where cod_material=436;
update salida_detalle_almacenes set costo_almacen=21.045 where cod_material=437;
update salida_detalle_almacenes set costo_almacen=23.501 where cod_material=438;
update salida_detalle_almacenes set costo_almacen=29.81 where cod_material=440;
update salida_detalle_almacenes set costo_almacen=45.562 where cod_material=441;
update salida_detalle_almacenes set costo_almacen=66.988 where cod_material=444;
update salida_detalle_almacenes set costo_almacen=55.302 where cod_material=445;
update salida_detalle_almacenes set costo_almacen=78.718 where cod_material=446;
update salida_detalle_almacenes set costo_almacen=243.563 where cod_material=447;
update salida_detalle_almacenes set costo_almacen=24.476 where cod_material=449;
update salida_detalle_almacenes set costo_almacen=27.567 where cod_material=450;
update salida_detalle_almacenes set costo_almacen=31.081 where cod_material=451;
update salida_detalle_almacenes set costo_almacen=46.622 where cod_material=452;
update salida_detalle_almacenes set costo_almacen=55.344 where cod_material=453;
update salida_detalle_almacenes set costo_almacen=58.138 where cod_material=456;
update salida_detalle_almacenes set costo_almacen=81.555 where cod_material=457;
update salida_detalle_almacenes set costo_almacen=31.801 where cod_material=458;
update salida_detalle_almacenes set costo_almacen=500.719 where cod_material=459;
update salida_detalle_almacenes set costo_almacen=115.599 where cod_material=460;
update salida_detalle_almacenes set costo_almacen=147.57 where cod_material=461;
update salida_detalle_almacenes set costo_almacen=153.794 where cod_material=462;
update salida_detalle_almacenes set costo_almacen=55.471 where cod_material=463;
update salida_detalle_almacenes set costo_almacen=77.49 where cod_material=464;
update salida_detalle_almacenes set costo_almacen=33.41 where cod_material=465;
update salida_detalle_almacenes set costo_almacen=34.849 where cod_material=466;
update salida_detalle_almacenes set costo_almacen=16.811 where cod_material=467;
update salida_detalle_almacenes set costo_almacen=21.173 where cod_material=468;
update salida_detalle_almacenes set costo_almacen=21.553 where cod_material=469;
update salida_detalle_almacenes set costo_almacen=31.716 where cod_material=470;
update salida_detalle_almacenes set costo_almacen=41.286 where cod_material=471;
update salida_detalle_almacenes set costo_almacen=50.433 where cod_material=472;
update salida_detalle_almacenes set costo_almacen=62.119 where cod_material=473;
update salida_detalle_almacenes set costo_almacen=71.943 where cod_material=474;
update salida_detalle_almacenes set costo_almacen=22.866 where cod_material=478;
update salida_detalle_almacenes set costo_almacen=15.71 where cod_material=479;
update salida_detalle_almacenes set costo_almacen=21.173 where cod_material=480;
update salida_detalle_almacenes set costo_almacen=35.866 where cod_material=481;
update salida_detalle_almacenes set costo_almacen=24.687 where cod_material=482;
update salida_detalle_almacenes set costo_almacen=40.947 where cod_material=483;
update salida_detalle_almacenes set costo_almacen=47.299 where cod_material=484;
update salida_detalle_almacenes set costo_almacen=54.159 where cod_material=485;
update salida_detalle_almacenes set costo_almacen=62.374 where cod_material=486;
update salida_detalle_almacenes set costo_almacen=69.996 where cod_material=487;
update salida_detalle_almacenes set costo_almacen=79.141 where cod_material=488;
update salida_detalle_almacenes set costo_almacen=45.605 where cod_material=489;
update salida_detalle_almacenes set costo_almacen=61.484 where cod_material=490;
update salida_detalle_almacenes set costo_almacen=72.324 where cod_material=491;
update salida_detalle_almacenes set costo_almacen=93.285 where cod_material=493;
update salida_detalle_almacenes set costo_almacen=87.822 where cod_material=494;
update salida_detalle_almacenes set costo_almacen=38.872 where cod_material=495;
update salida_detalle_almacenes set costo_almacen=43.276 where cod_material=496;
update salida_detalle_almacenes set costo_almacen=49.458 where cod_material=497;
update salida_detalle_almacenes set costo_almacen=291.243 where cod_material=500;
update salida_detalle_almacenes set costo_almacen=78.168 where cod_material=501;
update salida_detalle_almacenes set costo_almacen=299.711 where cod_material=502;
update salida_detalle_almacenes set costo_almacen=189.067 where cod_material=505;
update salida_detalle_almacenes set costo_almacen=28.117 where cod_material=506;
update salida_detalle_almacenes set costo_almacen=99.679 where cod_material=507;
update salida_detalle_almacenes set costo_almacen=97.307 where cod_material=508;
update salida_detalle_almacenes set costo_almacen=101.287 where cod_material=509;
update salida_detalle_almacenes set costo_almacen=116.785 where cod_material=510;
update salida_detalle_almacenes set costo_almacen=29.895 where cod_material=511;
update salida_detalle_almacenes set costo_almacen=32.648 where cod_material=512;
update salida_detalle_almacenes set costo_almacen=41.963 where cod_material=513;
update salida_detalle_almacenes set costo_almacen=43.361 where cod_material=514;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=515;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=516;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=517;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=518;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=519;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=520;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=521;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=523;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=524;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=525;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=526;
update salida_detalle_almacenes set costo_almacen=8.613 where cod_material=527;
update salida_detalle_almacenes set costo_almacen=8.613 where cod_material=528;
update salida_detalle_almacenes set costo_almacen=7.448 where cod_material=529;
update salida_detalle_almacenes set costo_almacen=7.448 where cod_material=530;
update salida_detalle_almacenes set costo_almacen=7.448 where cod_material=531;
update salida_detalle_almacenes set costo_almacen=5.685 where cod_material=532;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=533;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=534;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=535;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=536;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=537;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=538;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=539;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=540;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=541;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=542;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=543;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=544;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=545;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=546;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=547;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=548;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=549;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=550;
update salida_detalle_almacenes set costo_almacen=9.643 where cod_material=551;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=552;
update salida_detalle_almacenes set costo_almacen=5.685 where cod_material=553;
update salida_detalle_almacenes set costo_almacen=20.201 where cod_material=554;
update salida_detalle_almacenes set costo_almacen=13.978 where cod_material=555;
update salida_detalle_almacenes set costo_almacen=8.613 where cod_material=556;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=557;
update salida_detalle_almacenes set costo_almacen=5.685 where cod_material=558;
update salida_detalle_almacenes set costo_almacen=8.876 where cod_material=559;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=560;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=561;
update salida_detalle_almacenes set costo_almacen=10.101 where cod_material=562;
update salida_detalle_almacenes set costo_almacen=12.855 where cod_material=563;
update salida_detalle_almacenes set costo_almacen=11.529 where cod_material=564;
update salida_detalle_almacenes set costo_almacen=11.121 where cod_material=565;
update salida_detalle_almacenes set costo_almacen=7.346 where cod_material=566;
update salida_detalle_almacenes set costo_almacen=10.101 where cod_material=567;
update salida_detalle_almacenes set costo_almacen=12.855 where cod_material=568;
update salida_detalle_almacenes set costo_almacen=11.529 where cod_material=569;
update salida_detalle_almacenes set costo_almacen=11.121 where cod_material=570;
update salida_detalle_almacenes set costo_almacen=7.346 where cod_material=571;
update salida_detalle_almacenes set costo_almacen=10.101 where cod_material=572;
update salida_detalle_almacenes set costo_almacen=12.855 where cod_material=573;
update salida_detalle_almacenes set costo_almacen=11.529 where cod_material=574;
update salida_detalle_almacenes set costo_almacen=11.121 where cod_material=575;
update salida_detalle_almacenes set costo_almacen=7.346 where cod_material=576;
update salida_detalle_almacenes set costo_almacen=21.834 where cod_material=577;
update salida_detalle_almacenes set costo_almacen=19.997 where cod_material=578;
update salida_detalle_almacenes set costo_almacen=21.834 where cod_material=579;
update salida_detalle_almacenes set costo_almacen=19.997 where cod_material=580;
update salida_detalle_almacenes set costo_almacen=21.834 where cod_material=581;
update salida_detalle_almacenes set costo_almacen=19.997 where cod_material=582;
update salida_detalle_almacenes set costo_almacen=9.284 where cod_material=583;
update salida_detalle_almacenes set costo_almacen=8.06 where cod_material=584;
update salida_detalle_almacenes set costo_almacen=9.284 where cod_material=585;
update salida_detalle_almacenes set costo_almacen=8.06 where cod_material=586;
update salida_detalle_almacenes set costo_almacen=7.652 where cod_material=587;
update salida_detalle_almacenes set costo_almacen=7.346 where cod_material=588;
update salida_detalle_almacenes set costo_almacen=7.652 where cod_material=589;
update salida_detalle_almacenes set costo_almacen=7.346 where cod_material=590;
update salida_detalle_almacenes set costo_almacen=13.059 where cod_material=591;
update salida_detalle_almacenes set costo_almacen=13.059 where cod_material=592;
update salida_detalle_almacenes set costo_almacen=13.059 where cod_material=593;
update salida_detalle_almacenes set costo_almacen=13.978 where cod_material=595;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=597;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=598;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=599;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=600;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=601;
update salida_detalle_almacenes set costo_almacen=9.643 where cod_material=602;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=603;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=605;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=606;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=607;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=608;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=610;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=611;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=612;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=613;
update salida_detalle_almacenes set costo_almacen=9.795 where cod_material=614;
update salida_detalle_almacenes set costo_almacen=8.57 where cod_material=615;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=616;
update salida_detalle_almacenes set costo_almacen=5.713 where cod_material=617;
update salida_detalle_almacenes set costo_almacen=18.263 where cod_material=619;
update salida_detalle_almacenes set costo_almacen=9.795 where cod_material=620;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=621;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=622;
update salida_detalle_almacenes set costo_almacen=9.795 where cod_material=623;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=624;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=625;
update salida_detalle_almacenes set costo_almacen=9.795 where cod_material=626;
update salida_detalle_almacenes set costo_almacen=9.488 where cod_material=627;
update salida_detalle_almacenes set costo_almacen=7.984 where cod_material=628;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=629;
update salida_detalle_almacenes set costo_almacen=13.059 where cod_material=630;
update salida_detalle_almacenes set costo_almacen=18.263 where cod_material=631;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=632;
update salida_detalle_almacenes set costo_almacen=8.264 where cod_material=633;
update salida_detalle_almacenes set costo_almacen=9.897 where cod_material=634;
update salida_detalle_almacenes set costo_almacen=18.263 where cod_material=635;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=636;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=637;
update salida_detalle_almacenes set costo_almacen=5.713 where cod_material=638;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=639;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=640;
update salida_detalle_almacenes set costo_almacen=9.493 where cod_material=641;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=642;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=643;
update salida_detalle_almacenes set costo_almacen=5.713 where cod_material=644;
update salida_detalle_almacenes set costo_almacen=20.201 where cod_material=645;
update salida_detalle_almacenes set costo_almacen=8.57 where cod_material=646;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=647;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=648;
update salida_detalle_almacenes set costo_almacen=5.713 where cod_material=649;
update salida_detalle_almacenes set costo_almacen=8.57 where cod_material=650;
update salida_detalle_almacenes set costo_almacen=4.489 where cod_material=651;
update salida_detalle_almacenes set costo_almacen=4.489 where cod_material=652;
update salida_detalle_almacenes set costo_almacen=2.755 where cod_material=653;
update salida_detalle_almacenes set costo_almacen=2.755 where cod_material=654;
update salida_detalle_almacenes set costo_almacen=2.755 where cod_material=655;
update salida_detalle_almacenes set costo_almacen=4.33 where cod_material=656;
update salida_detalle_almacenes set costo_almacen=4.33 where cod_material=657;
update salida_detalle_almacenes set costo_almacen=4.33 where cod_material=658;
update salida_detalle_almacenes set costo_almacen=11.937 where cod_material=659;
update salida_detalle_almacenes set costo_almacen=11.937 where cod_material=660;
update salida_detalle_almacenes set costo_almacen=7.448 where cod_material=661;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=662;
update salida_detalle_almacenes set costo_almacen=7.856 where cod_material=663;
update salida_detalle_almacenes set costo_almacen=4.897 where cod_material=664;
update salida_detalle_almacenes set costo_almacen=4.897 where cod_material=665;
update salida_detalle_almacenes set costo_almacen=4.897 where cod_material=667;
update salida_detalle_almacenes set costo_almacen=4.183 where cod_material=668;
update salida_detalle_almacenes set costo_almacen=4.183 where cod_material=669;
update salida_detalle_almacenes set costo_almacen=3.571 where cod_material=672;
update salida_detalle_almacenes set costo_almacen=6.53 where cod_material=674;
update salida_detalle_almacenes set costo_almacen=8.876 where cod_material=675;
update salida_detalle_almacenes set costo_almacen=8.06 where cod_material=676;
update salida_detalle_almacenes set costo_almacen=8.57 where cod_material=678;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=679;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=680;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=681;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=682;
update salida_detalle_almacenes set costo_almacen=4.489 where cod_material=683;
update salida_detalle_almacenes set costo_almacen=4.489 where cod_material=684;
update salida_detalle_almacenes set costo_almacen=4.489 where cod_material=685;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=686;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=687;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=688;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=689;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=690;
update salida_detalle_almacenes set costo_almacen=9.781 where cod_material=691;
update salida_detalle_almacenes set costo_almacen=6.53 where cod_material=692;
update salida_detalle_almacenes set costo_almacen=8.06 where cod_material=693;
update salida_detalle_almacenes set costo_almacen=7.04 where cod_material=694;
update salida_detalle_almacenes set costo_almacen=8.876 where cod_material=695;
update salida_detalle_almacenes set costo_almacen=34.455 where cod_material=696;
update salida_detalle_almacenes set costo_almacen=53.193 where cod_material=697;
update salida_detalle_almacenes set costo_almacen=25.486 where cod_material=698;
update salida_detalle_almacenes set costo_almacen=70.243 where cod_material=699;
update salida_detalle_almacenes set costo_almacen=97.861 where cod_material=700;
update salida_detalle_almacenes set costo_almacen=986.242 where cod_material=701;
update salida_detalle_almacenes set costo_almacen=1158.164 where cod_material=702;
update salida_detalle_almacenes set costo_almacen=68.644 where cod_material=703;
update salida_detalle_almacenes set costo_almacen=91.644 where cod_material=706;
update salida_detalle_almacenes set costo_almacen=37.652 where cod_material=708;
update salida_detalle_almacenes set costo_almacen=42.004 where cod_material=709;
update salida_detalle_almacenes set costo_almacen=37.919 where cod_material=710;
update salida_detalle_almacenes set costo_almacen=42.181 where cod_material=711;
update salida_detalle_almacenes set costo_almacen=49.907 where cod_material=712;
update salida_detalle_almacenes set costo_almacen=63.671 where cod_material=714;
update salida_detalle_almacenes set costo_almacen=83.563 where cod_material=715;
update salida_detalle_almacenes set costo_almacen=49.374 where cod_material=716;
update salida_detalle_almacenes set costo_almacen=56.834 where cod_material=717;
update salida_detalle_almacenes set costo_almacen=63.938 where cod_material=718;
update salida_detalle_almacenes set costo_almacen=83.83 where cod_material=719;
update salida_detalle_almacenes set costo_almacen=59.942 where cod_material=720;
update salida_detalle_almacenes set costo_almacen=65.892 where cod_material=721;
update salida_detalle_almacenes set costo_almacen=62.339 where cod_material=722;
update salida_detalle_almacenes set costo_almacen=68.289 where cod_material=723;
update salida_detalle_almacenes set costo_almacen=60.208 where cod_material=724;
update salida_detalle_almacenes set costo_almacen=66.158 where cod_material=725;
update salida_detalle_almacenes set costo_almacen=23.977 where cod_material=726;
update salida_detalle_almacenes set costo_almacen=33.923 where cod_material=727;
update salida_detalle_almacenes set costo_almacen=16.961 where cod_material=728;
update salida_detalle_almacenes set costo_almacen=16.428 where cod_material=731;
update salida_detalle_almacenes set costo_almacen=21.135 where cod_material=732;
update salida_detalle_almacenes set costo_almacen=18.649 where cod_material=733;
update salida_detalle_almacenes set costo_almacen=23.71 where cod_material=734;
update salida_detalle_almacenes set costo_almacen=22.201 where cod_material=735;
update salida_detalle_almacenes set costo_almacen=24.243 where cod_material=737;
update salida_detalle_almacenes set costo_almacen=35.432 where cod_material=739;
update salida_detalle_almacenes set costo_almacen=20.602 where cod_material=741;
update salida_detalle_almacenes set costo_almacen=33.035 where cod_material=742;
update salida_detalle_almacenes set costo_almacen=44.668 where cod_material=743;
update salida_detalle_almacenes set costo_almacen=67.49 where cod_material=744;
update salida_detalle_almacenes set costo_almacen=20.336 where cod_material=745;
update salida_detalle_almacenes set costo_almacen=23.444 where cod_material=746;
update salida_detalle_almacenes set costo_almacen=27.44 where cod_material=747;
update salida_detalle_almacenes set costo_almacen=31.969 where cod_material=748;
update salida_detalle_almacenes set costo_almacen=42.448 where cod_material=749;
update salida_detalle_almacenes set costo_almacen=50.529 where cod_material=750;
update salida_detalle_almacenes set costo_almacen=33.212 where cod_material=751;
update salida_detalle_almacenes set costo_almacen=44.313 where cod_material=752;
update salida_detalle_almacenes set costo_almacen=67.756 where cod_material=753;
update salida_detalle_almacenes set costo_almacen=23.71 where cod_material=754;
update salida_detalle_almacenes set costo_almacen=27.706 where cod_material=755;
update salida_detalle_almacenes set costo_almacen=32.235 where cod_material=756;
update salida_detalle_almacenes set costo_almacen=42.625 where cod_material=757;
update salida_detalle_almacenes set costo_almacen=50.795 where cod_material=758;
update salida_detalle_almacenes set costo_almacen=88.181 where cod_material=760;
update salida_detalle_almacenes set costo_almacen=87.915 where cod_material=762;
update salida_detalle_almacenes set costo_almacen=108.517 where cod_material=763;
update salida_detalle_almacenes set costo_almacen=42.625 where cod_material=765;
update salida_detalle_almacenes set costo_almacen=17.346 where cod_material=3;
update salida_detalle_almacenes set costo_almacen=21.087 where cod_material=9;
update salida_detalle_almacenes set costo_almacen=23.249 where cod_material=11;
update salida_detalle_almacenes set costo_almacen=17.823 where cod_material=21;
update salida_detalle_almacenes set costo_almacen=20.752 where cod_material=22;
update salida_detalle_almacenes set costo_almacen=20.752 where cod_material=23;
update salida_detalle_almacenes set costo_almacen=38.628 where cod_material=26;
update salida_detalle_almacenes set costo_almacen=51.774 where cod_material=30;
update salida_detalle_almacenes set costo_almacen=48.986 where cod_material=36;
update salida_detalle_almacenes set costo_almacen=32.011 where cod_material=114;
update salida_detalle_almacenes set costo_almacen=21.22 where cod_material=115;
update salida_detalle_almacenes set costo_almacen=18.538 where cod_material=116;
update salida_detalle_almacenes set costo_almacen=4.906 where cod_material=151;
update salida_detalle_almacenes set costo_almacen=4.244 where cod_material=153;
update salida_detalle_almacenes set costo_almacen=4.456 where cod_material=155;
update salida_detalle_almacenes set costo_almacen=11.311 where cod_material=185;
update salida_detalle_almacenes set costo_almacen=16.852 where cod_material=196;
update salida_detalle_almacenes set costo_almacen=13.791 where cod_material=200;
update salida_detalle_almacenes set costo_almacen=15.335 where cod_material=204;
update salida_detalle_almacenes set costo_almacen=31.79 where cod_material=216;
update salida_detalle_almacenes set costo_almacen=16.376 where cod_material=241;
update salida_detalle_almacenes set costo_almacen=23.831 where cod_material=243;
update salida_detalle_almacenes set costo_almacen=2.894 where cod_material=251;
update salida_detalle_almacenes set costo_almacen=2.876 where cod_material=252;
update salida_detalle_almacenes set costo_almacen=2.956 where cod_material=254;
update salida_detalle_almacenes set costo_almacen=3.891 where cod_material=255;
update salida_detalle_almacenes set costo_almacen=3.9 where cod_material=256;
update salida_detalle_almacenes set costo_almacen=3.688 where cod_material=257;
update salida_detalle_almacenes set costo_almacen=3.653 where cod_material=258;
update salida_detalle_almacenes set costo_almacen=3.565 where cod_material=259;
update salida_detalle_almacenes set costo_almacen=3.768 where cod_material=260;
update salida_detalle_almacenes set costo_almacen=5.726 where cod_material=271;
update salida_detalle_almacenes set costo_almacen=5.753 where cod_material=272;
update salida_detalle_almacenes set costo_almacen=6.141 where cod_material=275;
update salida_detalle_almacenes set costo_almacen=21.758 where cod_material=292;
update salida_detalle_almacenes set costo_almacen=33.405 where cod_material=306;
update salida_detalle_almacenes set costo_almacen=8.964 where cod_material=319;
update salida_detalle_almacenes set costo_almacen=9.538 where cod_material=320;
update salida_detalle_almacenes set costo_almacen=9.538 where cod_material=321;
update salida_detalle_almacenes set costo_almacen=70.631 where cod_material=330;
update salida_detalle_almacenes set costo_almacen=88.118 where cod_material=331;
update salida_detalle_almacenes set costo_almacen=27.143 where cod_material=346;
update salida_detalle_almacenes set costo_almacen=53.947 where cod_material=348;
update salida_detalle_almacenes set costo_almacen=25.576 where cod_material=349;
update salida_detalle_almacenes set costo_almacen=55.429 where cod_material=352;
update salida_detalle_almacenes set costo_almacen=30.53 where cod_material=355;
update salida_detalle_almacenes set costo_almacen=27.82 where cod_material=358;
update salida_detalle_almacenes set costo_almacen=55.514 where cod_material=360;
update salida_detalle_almacenes set costo_almacen=27.694 where cod_material=362;
update salida_detalle_almacenes set costo_almacen=30.318 where cod_material=363;
update salida_detalle_almacenes set costo_almacen=112.593 where cod_material=372;
update salida_detalle_almacenes set costo_almacen=26.592 where cod_material=376;
update salida_detalle_almacenes set costo_almacen=28.964 where cod_material=404;
update salida_detalle_almacenes set costo_almacen=41.286 where cod_material=407;
update salida_detalle_almacenes set costo_almacen=62.077 where cod_material=408;
update salida_detalle_almacenes set costo_almacen=59.959 where cod_material=415;
update salida_detalle_almacenes set costo_almacen=55.683 where cod_material=420;
update salida_detalle_almacenes set costo_almacen=55.64 where cod_material=423;
update salida_detalle_almacenes set costo_almacen=35.019 where cod_material=424;
update salida_detalle_almacenes set costo_almacen=46.875 where cod_material=426;
update salida_detalle_almacenes set costo_almacen=53.396 where cod_material=427;
update salida_detalle_almacenes set costo_almacen=26.466 where cod_material=439;
update salida_detalle_almacenes set costo_almacen=54.116 where cod_material=442;
update salida_detalle_almacenes set costo_almacen=60.594 where cod_material=443;
update salida_detalle_almacenes set costo_almacen=21.85 where cod_material=448;
update salida_detalle_almacenes set costo_almacen=62.119 where cod_material=454;
update salida_detalle_almacenes set costo_almacen=68.894 where cod_material=455;
update salida_detalle_almacenes set costo_almacen=16.388 where cod_material=475;
update salida_detalle_almacenes set costo_almacen=17.7 where cod_material=476;
update salida_detalle_almacenes set costo_almacen=19.14 where cod_material=477;
update salida_detalle_almacenes set costo_almacen=82.36 where cod_material=492;
update salida_detalle_almacenes set costo_almacen=28.922 where cod_material=498;
update salida_detalle_almacenes set costo_almacen=38.364 where cod_material=499;
update salida_detalle_almacenes set costo_almacen=80.116 where cod_material=503;
update salida_detalle_almacenes set costo_almacen=383.934 where cod_material=504;
update salida_detalle_almacenes set costo_almacen=7.958 where cod_material=522;
update salida_detalle_almacenes set costo_almacen=20.201 where cod_material=594;
update salida_detalle_almacenes set costo_almacen=20.201 where cod_material=596;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=604;
update salida_detalle_almacenes set costo_almacen=9.692 where cod_material=609;
update salida_detalle_almacenes set costo_almacen=8.57 where cod_material=618;
update salida_detalle_almacenes set costo_almacen=4.897 where cod_material=666;
update salida_detalle_almacenes set costo_almacen=3.571 where cod_material=670;
update salida_detalle_almacenes set costo_almacen=3.571 where cod_material=671;
update salida_detalle_almacenes set costo_almacen=3.571 where cod_material=673;
update salida_detalle_almacenes set costo_almacen=13.978 where cod_material=677;
update salida_detalle_almacenes set costo_almacen=82.853 where cod_material=704;
update salida_detalle_almacenes set costo_almacen=80.722 where cod_material=705;
update salida_detalle_almacenes set costo_almacen=92.621 where cod_material=707;
update salida_detalle_almacenes set costo_almacen=57.544 where cod_material=713;
update salida_detalle_almacenes set costo_almacen=59.054 where cod_material=729;
update salida_detalle_almacenes set costo_almacen=15.363 where cod_material=730;
update salida_detalle_almacenes set costo_almacen=26.463 where cod_material=736;
update salida_detalle_almacenes set costo_almacen=33.745 where cod_material=738;
update salida_detalle_almacenes set costo_almacen=58.077 where cod_material=740;
update salida_detalle_almacenes set costo_almacen=44.668 where cod_material=759;
update salida_detalle_almacenes set costo_almacen=44.49 where cod_material=761;
update salida_detalle_almacenes set costo_almacen=107.806 where cod_material=764;
update salida_detalle_almacenes set costo_almacen=6.829 where cod_material=802;
update salida_detalle_almacenes set costo_almacen=100 where cod_material=805;
update salida_detalle_almacenes set costo_almacen=25 where cod_material=806;
update salida_detalle_almacenes set costo_almacen=15 where cod_material=807;
update salida_detalle_almacenes set costo_almacen=1 where cod_material=809;
update salida_detalle_almacenes set costo_almacen=6.829 where cod_material=801;
update salida_detalle_almacenes set costo_almacen=23.62 where cod_material=808;
update salida_detalle_almacenes set costo_almacen=59.07 where cod_material=810;
update salida_detalle_almacenes set costo_almacen=20.99 where cod_material=817;
update salida_detalle_almacenes set costo_almacen=52.01 where cod_material=815;
update salida_detalle_almacenes set costo_almacen=20.0316666666667 where cod_material=838;
update salida_detalle_almacenes set costo_almacen=74.88 where cod_material=819;
update salida_detalle_almacenes set costo_almacen=59.07 where cod_material=811;
update salida_detalle_almacenes set costo_almacen=11.15 where cod_material=816;
update salida_detalle_almacenes set costo_almacen=44.58 where cod_material=818;
update salida_detalle_almacenes set costo_almacen=17.395 where cod_material=841;
update salida_detalle_almacenes set costo_almacen=21 where cod_material=840;
update salida_detalle_almacenes set costo_almacen=30.1 where cod_material=839;
update salida_detalle_almacenes set costo_almacen=16.8875 where cod_material=820;
update salida_detalle_almacenes set costo_almacen=12.17 where cod_material=813;";

if (!$enlaceCon->multi_query($sql)) {
    echo "Error en el procesamiento: (" . $enlaceCon->errno . ") " . $enlaceCon->error;
}

do {
    if ($resultado = $enlaceCon->store_result()) {
        var_dump($resultado->fetch_all(MYSQLI_ASSOC));
        $resultado->free();
    }
} while ($enlaceCon->more_results() && $enlaceCon->next_result());

echo "<span class='texto' style='color:red;' align='center'>Costos Reprocesados Parte 1!</span>";

$sql = "update salida_detalle_almacenes set costo_almacen=125.2668 where cod_material=510 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=91.6 where cod_material=501 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=51.67 where cod_material=411 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=45.94 where cod_material=495 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=51.67 where cod_material=412 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=47.23 where cod_material=906 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=130.71 where cod_material=927 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=50.36 where cod_material=441 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=99.44 where cod_material=917 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=79.67 where cod_material=938 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=54.69 where cod_material=907 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=51.54 where cod_material=452 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=61.72 where cod_material=453 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=60.41 where cod_material=442 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=120.47 where cod_material=919 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=67.86 where cod_material=908 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=98.49 where cod_material=940 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=133.4 where cod_material=920 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=77.17 where cod_material=909 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=107.15 where cod_material=941 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=69.22 where cod_material=454 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=157.5 where cod_material=928 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=67.64 where cod_material=443 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=85.61 where cod_material=910 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=122.05 where cod_material=942 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=76.9 where cod_material=455 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=177.8 where cod_material=929 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=74.362727272727 where cod_material=444 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=78.48 where cod_material=487 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=128.14 where cod_material=943 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=88.7 where cod_material=488 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=227.65 where cod_material=930 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=44.84 where cod_material=407 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=15.65 where cod_material=370 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=27.68 where cod_material=366 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=30 where cod_material=367 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=33.06 where cod_material=368 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=97.14 where cod_material=365 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=74.56 where cod_material=330 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=96.96 where cod_material=331 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=92.7 where cod_material=334 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=96.03 where cod_material=335 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=68.24 where cod_material=333 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=22.29 where cod_material=402 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.43 where cod_material=911 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=27.02 where cod_material=482 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=27.58 where cod_material=403 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.44 where cod_material=498 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=38.02 where cod_material=945 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=34.48 where cod_material=458 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=35.89 where cod_material=951 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.46 where cod_material=404 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=44.59 where cod_material=428 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=43.46 where cod_material=400 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=54.63 where cod_material=922 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=39.04 where cod_material=405 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=53.58 where cod_material=429 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=52 where cod_material=401 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=102.074 where cod_material=493 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=16.47 where cod_material=417 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=22.75 where cod_material=437 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=66.2 where cod_material=913 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=51.59 where cod_material=933 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=24.13 where cod_material=903 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=23.62 where cod_material=448 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.253548387097 where cod_material=349 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.75 where cod_material=353 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.71 where cod_material=361 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=25.97 where cod_material=932 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.75 where cod_material=345 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.551162790698 where cod_material=357 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=25.45 where cod_material=438 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=71.41 where cod_material=914 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=56.62 where cod_material=934 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.35 where cod_material=904 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.46 where cod_material=449 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=28.5 where cod_material=350 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.04 where cod_material=354 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.04 where cod_material=362 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=21.58 where cod_material=418 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=21.45 where cod_material=946 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.08 where cod_material=346 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=28.7425 where cod_material=358 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=28.81 where cod_material=439 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=79.25 where cod_material=915 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=63.39 where cod_material=935 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.32 where cod_material=905 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=29.9 where cod_material=450 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=80.86 where cod_material=924 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.5525 where cod_material=351 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.93 where cod_material=355 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.84 where cod_material=363 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.440869565217 where cod_material=347 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=31.5925 where cod_material=359 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=32.47 where cod_material=440 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=91.03 where cod_material=916 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=75.56 where cod_material=936 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=33.73 where cod_material=451 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=99.35 where cod_material=925 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=81.97 where cod_material=937 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=120.71 where cod_material=926 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=37.58 where cod_material=419 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=62.78 where cod_material=420 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=62.71 where cod_material=423 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=37.65 where cod_material=422 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=38.43 where cod_material=956 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=62.61 where cod_material=958 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=41.58 where cod_material=957 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=68.41 where cod_material=959 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=36.38 where cod_material=421 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=65.04 where cod_material=952 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=36.38 where cod_material=424 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=65.04 where cod_material=953 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=41.43 where cod_material=499 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=41.55 where cod_material=414 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=65.09 where cod_material=415 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=58.61 where cod_material=923 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=194.68 where cod_material=931 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=44.85 where cod_material=409 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=49.61 where cod_material=954 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=79.6 where cod_material=955 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=91.71 where cod_material=918 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=63.53 where cod_material=456 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=58.59 where cod_material=348 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=56.29 where cod_material=352 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=60.73 where cod_material=445 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=58.192857142857 where cod_material=356 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=91.84 where cod_material=457 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=88.97 where cod_material=446 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=57.28875 where cod_material=364 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=56.948095238095 where cod_material=360 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=204.86 where cod_material=505 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=544.5 where cod_material=459 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=241.61 where cod_material=860 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=541.16 where cod_material=901 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=423.79 where cod_material=902 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=270.01 where cod_material=447 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=13.33 where cod_material=947 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=16.33 where cod_material=948 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=20.32 where cod_material=949 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=21.9 where cod_material=950 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=24.56 where cod_material=475 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=26.258139534884 where cod_material=476 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=27.7 where cod_material=477 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=30.17 where cod_material=900 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=34.96 where cod_material=478 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=42.11 where cod_material=912 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=70.57 where cod_material=939 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=109.81 where cod_material=944 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=131.11 where cod_material=921 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=169.03 where cod_material=462 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2023-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1026 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1027 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1028 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1029 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1030 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1031 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=6.67 where cod_material=1032 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=8.34 where cod_material=1033 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=13.33 where cod_material=1034 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=15 where cod_material=1035 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');

update salida_detalle_almacenes set costo_almacen=11.67 where cod_material=1036 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=10 where cod_material=1037 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');
update salida_detalle_almacenes set costo_almacen=25 where cod_material=1038 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');


update salida_detalle_almacenes set costo_almacen=2.798416 where cod_material=1024 and cod_salida_almacen in (select s.cod_salida_almacenes from salida_almacenes s where s.fecha>='2020-03-10');";




if (!$enlaceCon->multi_query($sql)) {
    echo "Error en el procesamiento: (" . $enlaceCon->errno . ") " . $enlaceCon->error;
}

do {
    if ($resultado = $enlaceCon->store_result()) {
        var_dump($resultado->fetch_all(MYSQLI_ASSOC));
        $resultado->free();
    }
} while ($enlaceCon->more_results() && $enlaceCon->next_result());

echo "<span class='texto' style='color:red;' align='center'>Costos Reprocesados Parte 2!</span>";


?>